/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as ImagesImport } from './routes/images'
import { Route as SplatImport } from './routes/$'
import { Route as IndexImport } from './routes/index'
import { Route as ImagesImageIdImport } from './routes/images_.$imageId'

// Create/Update Routes

const ImagesRoute = ImagesImport.update({
  id: '/images',
  path: '/images',
  getParentRoute: () => rootRoute,
} as any)

const SplatRoute = SplatImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const ImagesImageIdRoute = ImagesImageIdImport.update({
  id: '/images_/$imageId',
  path: '/images/$imageId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatImport
      parentRoute: typeof rootRoute
    }
    '/images': {
      id: '/images'
      path: '/images'
      fullPath: '/images'
      preLoaderRoute: typeof ImagesImport
      parentRoute: typeof rootRoute
    }
    '/images_/$imageId': {
      id: '/images_/$imageId'
      path: '/images/$imageId'
      fullPath: '/images/$imageId'
      preLoaderRoute: typeof ImagesImageIdImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/images': typeof ImagesRoute
  '/images/$imageId': typeof ImagesImageIdRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/images': typeof ImagesRoute
  '/images/$imageId': typeof ImagesImageIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/images': typeof ImagesRoute
  '/images_/$imageId': typeof ImagesImageIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/$' | '/images' | '/images/$imageId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$' | '/images' | '/images/$imageId'
  id: '__root__' | '/' | '/$' | '/images' | '/images_/$imageId'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  ImagesRoute: typeof ImagesRoute
  ImagesImageIdRoute: typeof ImagesImageIdRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  ImagesRoute: ImagesRoute,
  ImagesImageIdRoute: ImagesImageIdRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/$",
        "/images",
        "/images_/$imageId"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/$": {
      "filePath": "$.tsx"
    },
    "/images": {
      "filePath": "images.tsx"
    },
    "/images_/$imageId": {
      "filePath": "images_.$imageId.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
